nvim-symlink:
	./script/symlink/nvim.sh
zsh-symlink:
	./script/symlink/zsh.sh
sway-symlink:
	./script/symlink/sway.sh
tmux-symlink:
	./script/symlink/tmux.sh
script-symlink:
	./script/symlink/script.sh
