# Change prefix
unbind C-b
set-option -g prefix C-space
bind-key C-space send-prefix

# enable mouse mode
set -g mouse on

# previous / next window
bind-key -n M-Left previous-window
bind-key -n M-Right next-window
# bind C-d to detach
# bind-key -n C-d detach
